// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia.Data;

#nullable disable

namespace Persistencia.Data.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20230928133002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entities.CargoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCargoEmpleado")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreCargo");

                    b.HasKey("Id");

                    b.ToTable("CargoEmpleado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Medico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Farmaceutico"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cajero"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Repartidor"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Contador"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.CategoriaMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCategoriaMedicamento")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreMedicamento");

                    b.HasKey("Id");

                    b.ToTable("CategoriaMedicamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Analgesico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Antiinflamatorio"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Antibiotico"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Antiulceroso"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCita")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoCitaId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoCita_Id");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaCita");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("Medico_Id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("Usuario_Id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCitaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cita", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoCitaId = 1,
                            FechaCita = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            EstadoCitaId = 6,
                            FechaCita = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCiudad")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("Departamento_Id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreCiudad");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Ciudad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 6,
                            Nombre = "Bogota"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 2,
                            Nombre = "Medellin"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 4,
                            Nombre = "Cartagena"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 1,
                            Nombre = "Cali"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 2,
                            Nombre = "Barranquilla"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 4,
                            Nombre = "Santa Marta"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 6,
                            Nombre = "Bucaramanga"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCompra")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaCompra");

                    b.Property<int>("MetodoDePagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoDePago_Id");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NumeroFactura");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("Proveedor_Id");

                    b.HasKey("Id");

                    b.HasIndex("MetodoDePagoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compra", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCompra = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 2,
                            NumeroFactura = "1112245",
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaCompra = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 3,
                            NumeroFactura = "324324234",
                            ProveedorId = 2
                        },
                        new
                        {
                            Id = 3,
                            FechaCompra = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 4,
                            NumeroFactura = "3245435325",
                            ProveedorId = 4
                        },
                        new
                        {
                            Id = 4,
                            FechaCompra = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 1,
                            NumeroFactura = "3453245435",
                            ProveedorId = 3
                        },
                        new
                        {
                            Id = 5,
                            FechaCompra = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 2,
                            NumeroFactura = "4343255",
                            ProveedorId = 2
                        },
                        new
                        {
                            Id = 6,
                            FechaCompra = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 3,
                            NumeroFactura = "345325345",
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 7,
                            FechaCompra = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 4,
                            NumeroFactura = "34523452345",
                            ProveedorId = 2
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartamento")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreDepartamento");

                    b.Property<int?>("PaisId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Pais_Id");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Departamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Putumayo",
                            PaisId = 24
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Huila",
                            PaisId = 24
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "La Guajira",
                            PaisId = 24
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Magdalena",
                            PaisId = 24
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Meta",
                            PaisId = 24
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Santander",
                            PaisId = 24
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDireccion")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CiudadId")
                        .HasColumnType("int")
                        .HasColumnName("Ciudad_Id");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int")
                        .HasColumnName("CodigoPostal");

                    b.Property<int>("FarmaciaId")
                        .HasColumnType("int")
                        .HasColumnName("Farmacia_Id");

                    b.Property<string>("NombreDireccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Direccion");

                    b.Property<int>("NroDireccion")
                        .HasColumnType("int")
                        .HasColumnName("NroDireccion");

                    b.Property<int>("TipoDireccionId")
                        .HasColumnType("int")
                        .HasColumnName("TipoDireccion_Id");

                    b.Property<int>("TipoViaId")
                        .HasColumnType("int")
                        .HasColumnName("TipoVia_Id");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("FarmaciaId");

                    b.HasIndex("TipoDireccionId");

                    b.HasIndex("TipoViaId");

                    b.ToTable("Direccion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CiudadId = 7,
                            CodigoPostal = 680001,
                            FarmaciaId = 1,
                            NombreDireccion = "Cristal Alto Casa 1 piso2 Peatonal",
                            NroDireccion = 5,
                            TipoDireccionId = 1,
                            TipoViaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CiudadId = 7,
                            CodigoPostal = 680001,
                            FarmaciaId = 1,
                            NombreDireccion = "Barrio Santa Ana",
                            NroDireccion = 249,
                            TipoDireccionId = 1,
                            TipoViaId = 8
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar")
                        .HasColumnName("Apellidos");

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("Cargo_Id");

                    b.Property<int>("FarmaciaId")
                        .HasColumnType("int")
                        .HasColumnName("Farmacia_Id");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaContratacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombres");

                    b.Property<string>("Sueldo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Sueldo");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("FarmaciaId");

                    b.ToTable("Empleado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Perez Numa",
                            CargoId = 1,
                            FarmaciaId = 1,
                            FechaContratacion = new DateTime(2023, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Juan David",
                            Sueldo = "5000000"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Alucema Torres",
                            CargoId = 1,
                            FarmaciaId = 1,
                            FechaContratacion = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Konny Liseth",
                            Sueldo = "2000000"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Morales Silva",
                            CargoId = 2,
                            FarmaciaId = 1,
                            FechaContratacion = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Maria Angelica",
                            Sueldo = "2200000"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.EstadoCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEstadoCita")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreEstado");

                    b.HasKey("Id");

                    b.ToTable("EstadoCita", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Programada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Confirmada"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "No confirmada"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Atendida"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "En espera"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Reprogramada"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Rechazada"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Farmacia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFarmacia")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaInauguracion")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaInauguracion");

                    b.Property<string>("NombreFarmacia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreFarmacia");

                    b.Property<string>("NumeroContacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("NumeroContacto");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Propietario");

                    b.Property<string>("URLSitioWeb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("URLSitioWeb");

                    b.HasKey("Id");

                    b.ToTable("Farmacia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaInauguracion = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreFarmacia = "FarmacooParte2",
                            NumeroContacto = "3208818203",
                            Propietario = "Sicer Andres Brito Gutierrez",
                            URLSitioWeb = "https://github.com/SicerBrito"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.FormulaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFormulaMedica")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DuracionTratamiento")
                        .HasColumnType("int")
                        .HasColumnName("DuracionTratamiento");

                    b.Property<DateTime>("FechaPrescripcion")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaPrescripcion");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Indicaciones");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("Medico_Id");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("Paciente_Id");

                    b.Property<string>("Posologia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Posologia");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("FormulaMedica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuracionTratamiento = 30,
                            FechaPrescripcion = new DateTime(2023, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Indicaciones = "Hipertension, Diabetes",
                            MedicoId = 2,
                            PacienteId = 2,
                            Posologia = "Aspirina: 1 tableta diaria después de la comida"
                        },
                        new
                        {
                            Id = 2,
                            DuracionTratamiento = 90,
                            FechaPrescripcion = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Indicaciones = "Chequeo de rutina",
                            MedicoId = 2,
                            PacienteId = 1,
                            Posologia = "Ventolin: 2 inhalaciones cuando sea necesario"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.FormulaMedicamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFormulaMedicamentos")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FomulaMedicaId")
                        .HasColumnType("int")
                        .HasColumnName("FomulaMedica_Id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("Medicamento_Id");

                    b.HasKey("Id");

                    b.HasIndex("FomulaMedicaId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("FormulaMedicamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FomulaMedicaId = 1,
                            MedicamentoId = 4
                        },
                        new
                        {
                            Id = 2,
                            FomulaMedicaId = 2,
                            MedicamentoId = 1
                        },
                        new
                        {
                            Id = 3,
                            FomulaMedicaId = 2,
                            MedicamentoId = 3
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGenero")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreGenero");

                    b.HasKey("Id");

                    b.ToTable("Genero", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Femenino"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Otro"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Helicoptero"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Prefiero no decirlo"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.HistorialMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHistorialMedico")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Diagnostico");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("Medico_Id");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Observaciones");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("Paciente_Id");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Tratamiento");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("HistorialMedico", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnostico = "Hipertensión, Diabetes",
                            MedicoId = 1,
                            Observaciones = "Paciente en seguimiento regular",
                            PacienteId = 1,
                            Tratamiento = "Medicamentos recetados, dieta, ejercicio"
                        },
                        new
                        {
                            Id = 2,
                            Diagnostico = "Asma, Alergias",
                            MedicoId = 1,
                            Observaciones = "Ocasionales episodios asmáticos.",
                            PacienteId = 1,
                            Tratamiento = "Inhalador de rescate, evitar alérgenos "
                        },
                        new
                        {
                            Id = 3,
                            Diagnostico = "Sin problemas de salud",
                            MedicoId = 1,
                            Observaciones = "Chequeo de rutina sin novedades",
                            PacienteId = 1,
                            Tratamiento = "Medicamento, control de presión "
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdInventario")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("Compra_Id");

                    b.Property<int>("FarmaciaId")
                        .HasColumnType("int")
                        .HasColumnName("Farmacia_Id");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("Usuario_Id");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("FarmaciaId");

                    b.HasIndex("VentaId");

                    b.ToTable("Inventario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompraId = 5,
                            FarmaciaId = 1,
                            VentaId = 2
                        },
                        new
                        {
                            Id = 2,
                            CompraId = 7,
                            FarmaciaId = 1,
                            VentaId = 1
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedicamento")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaMedicamento_Id");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaExpiracion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreMedicamento");

                    b.Property<int>("PresentacionId")
                        .HasColumnType("int")
                        .HasColumnName("PresentacionMedicamento_Id");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("Proveedor_Id");

                    b.Property<long>("Stock")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Stock");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoMedicamento_Id");

                    b.Property<string>("ValorUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ValorUnidad");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PresentacionId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoId");

                    b.ToTable("Medicamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            FechaExpiracion = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Aspirina",
                            PresentacionId = 2,
                            ProveedorId = 2,
                            Stock = 80L,
                            TipoId = 1,
                            ValorUnidad = "2000"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            FechaExpiracion = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ibuprofeno",
                            PresentacionId = 2,
                            ProveedorId = 2,
                            Stock = 20L,
                            TipoId = 2,
                            ValorUnidad = "5000"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            FechaExpiracion = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Paracetamol",
                            PresentacionId = 2,
                            ProveedorId = 2,
                            Stock = 45L,
                            TipoId = 1,
                            ValorUnidad = "1000"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            FechaExpiracion = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Amoxicilina",
                            PresentacionId = 2,
                            ProveedorId = 2,
                            Stock = 70L,
                            TipoId = 2,
                            ValorUnidad = "3500"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            FechaExpiracion = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Omeprazol",
                            PresentacionId = 2,
                            ProveedorId = 2,
                            Stock = 10L,
                            TipoId = 2,
                            ValorUnidad = "2200"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.MedicamentosComprados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedicamentosComprados")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadCompra")
                        .HasColumnType("int")
                        .HasColumnName("CantidadCompra");

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("Compra_Id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("Medico_Id");

                    b.Property<string>("ValorTotalCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ValorTotalCompra");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("MedicamentosComprados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadCompra = 5,
                            CompraId = 1,
                            MedicamentoId = 5,
                            ValorTotalCompra = "50000"
                        },
                        new
                        {
                            Id = 2,
                            CantidadCompra = 2,
                            CompraId = 2,
                            MedicamentoId = 1,
                            ValorTotalCompra = "60000"
                        },
                        new
                        {
                            Id = 3,
                            CantidadCompra = 21,
                            CompraId = 1,
                            MedicamentoId = 3,
                            ValorTotalCompra = "21000"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.MedicamentosVendidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedicamentosVendidos")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int")
                        .HasColumnName("CantidadVendida");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("Medicamento_Id");

                    b.Property<string>("ValorTotalVenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ValorTotalVenta");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("Venta_Id");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("VentaId");

                    b.ToTable("MedicamentosVendidos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadVendida = 2,
                            MedicamentoId = 1,
                            ValorTotalVenta = "60000",
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadVendida = 21,
                            MedicamentoId = 3,
                            ValorTotalVenta = "21000",
                            VentaId = 2
                        },
                        new
                        {
                            Id = 3,
                            CantidadVendida = 5,
                            MedicamentoId = 5,
                            ValorTotalVenta = "50000",
                            VentaId = 1
                        });
                });

            modelBuilder.Entity("Dominio.Entities.MetodoDePago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMetodoDePago")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreMetodo");

                    b.HasKey("Id");

                    b.ToTable("MetodoDePago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tarjeta de credito"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tarjeta de debito"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cheque"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Transferencia bancaria"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPaciente")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Apellidos");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaNacimiento");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int")
                        .HasColumnName("Genero_Id");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombres");

                    b.Property<string>("NumeroContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NroContacto");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Paciente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Polanco Silva",
                            FechaNacimiento = new DateTime(2003, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            Nombres = "Owell Andry",
                            NumeroContacto = "3221243579"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Torres Alvares",
                            FechaNacimiento = new DateTime(2003, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            Nombres = "Sherman Andres",
                            NumeroContacto = "6355050"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPais")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombrePais");

                    b.HasKey("Id");

                    b.ToTable("Pais", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mexico"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Europa"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Asia"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Africa"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Oceania"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "China"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "India"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Indonesia"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Japon"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Marruecos"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Nigeria"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Rusia"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Sudafrica"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Tailandia"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Austria"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Belgica"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Bulgaria"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Costa Rica"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Presentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPresentacion")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Presentacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Caja de 30 tabletas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Botella de 100 capsulas"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Caja de 50 tabletas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Botella de 30 capsulas"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Caja de 60 capsulas"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdProveedor")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Nombres");

                    b.Property<string>("NroContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NroContacto");

                    b.HasKey("Id");

                    b.ToTable("Proveedor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Apellido Proveedor A",
                            Nombres = "Nombres Proveedor A",
                            NroContacto = "3208818203"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Apellido Proveedor B",
                            Nombres = "Nombres Proveedor B",
                            NroContacto = "3208818203"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Apellido Proveedor C",
                            Nombres = "Nombres Proveedor C",
                            NroContacto = "3208818203"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Apellido Proveedor D",
                            Nombres = "Nombres Proveedor D",
                            NroContacto = "3208818203"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "ApellidoA",
                            Nombres = "ProveedorA",
                            NroContacto = "3208818203"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Rol")
                        .HasAnnotation("MySqlValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreRol");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Empleado"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.TipoDireccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoDireccion")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreDireccion");

                    b.HasKey("Id");

                    b.ToTable("TipoDireccion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Residencial"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Distrital"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Oficina Principal"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Comercial"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.TipoMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoMedicamento")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreTipo");

                    b.HasKey("Id");

                    b.ToTable("TipoMedicamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tableta"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Capsula"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.TipoVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoVia")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("Abreviatura");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("NombreTipoVia");

                    b.HasKey("Id");

                    b.ToTable("TipoVia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "Cal",
                            Nombre = "Calle"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "Av",
                            Nombre = "Avenida"
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "Blvd",
                            Nombre = "Boulevard"
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "Carr",
                            Nombre = "Carretera"
                        },
                        new
                        {
                            Id = 5,
                            Abreviatura = "Pso",
                            Nombre = "Paseo"
                        },
                        new
                        {
                            Id = 6,
                            Abreviatura = "Cam",
                            Nombre = "Camino"
                        },
                        new
                        {
                            Id = 7,
                            Abreviatura = "Plz",
                            Nombre = "Plaza"
                        },
                        new
                        {
                            Id = 8,
                            Abreviatura = "Via",
                            Nombre = "Via"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario")
                        .HasAnnotation("MySqlValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "britodelgado514@gmail.com",
                            Password = "123456",
                            Username = "Sicer Brito"
                        },
                        new
                        {
                            Id = 2,
                            Email = "angedeveloper@gmail.com",
                            Password = "123",
                            Username = "Angelica Morales"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_UsuarioRol")
                        .HasAnnotation("MySqlValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("Rol_Id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("Usuario_Id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            RolId = 3,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdVenta")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_Id");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("DateTime")
                        .HasColumnName("FechaVenta");

                    b.Property<int>("MetodoDePagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoDePago_Id");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("NumeroFactura");

                    b.Property<int>("VentaEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("VentaEmpleado_Id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MetodoDePagoId");

                    b.HasIndex("VentaEmpleadoId");

                    b.ToTable("Venta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            FechaVenta = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 1,
                            NumeroFactura = "5363634231",
                            VentaEmpleadoId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            FechaVenta = new DateTime(2023, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MetodoDePagoId = 1,
                            NumeroFactura = "473567356465",
                            VentaEmpleadoId = 2
                        });
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("Dominio.Entities.Cita", b =>
                {
                    b.HasOne("Dominio.Entities.EstadoCita", "EstadoCitas")
                        .WithMany("Citas")
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Empleado", "Empleados")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuario", "Usuarios")
                        .WithMany("Citas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("EstadoCitas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Dominio.Entities.Ciudad", b =>
                {
                    b.HasOne("Dominio.Entities.Departamento", "Departamentos")
                        .WithMany("Ciudades")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Compra", b =>
                {
                    b.HasOne("Dominio.Entities.MetodoDePago", "MetodosDePagos")
                        .WithMany("Compras")
                        .HasForeignKey("MetodoDePagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Proveedor", "Proveedores")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodosDePagos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Dominio.Entities.Departamento", b =>
                {
                    b.HasOne("Dominio.Entities.Pais", "Paises")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paises");
                });

            modelBuilder.Entity("Dominio.Entities.Direccion", b =>
                {
                    b.HasOne("Dominio.Entities.Ciudad", "Ciudades")
                        .WithMany("Direcciones")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Farmacia", "Farmacias")
                        .WithMany("Direcciones")
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.TipoDireccion", "TipoDirecciones")
                        .WithMany("Direcciones")
                        .HasForeignKey("TipoDireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.TipoVia", "TipoVias")
                        .WithMany("Direcciones")
                        .HasForeignKey("TipoViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudades");

                    b.Navigation("Farmacias");

                    b.Navigation("TipoDirecciones");

                    b.Navigation("TipoVias");
                });

            modelBuilder.Entity("Dominio.Entities.Empleado", b =>
                {
                    b.HasOne("Dominio.Entities.CargoEmpleado", "Cargos")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Farmacia", "Farmacias")
                        .WithMany("Empleados")
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargos");

                    b.Navigation("Farmacias");
                });

            modelBuilder.Entity("Dominio.Entities.FormulaMedica", b =>
                {
                    b.HasOne("Dominio.Entities.Empleado", "Empleados")
                        .WithMany("FormulasMedicas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Paciente", "Pacientes")
                        .WithMany("FormulasMedicas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Dominio.Entities.FormulaMedicamentos", b =>
                {
                    b.HasOne("Dominio.Entities.FormulaMedica", "FormulasMedicas")
                        .WithMany("FormulaMedicamentos")
                        .HasForeignKey("FomulaMedicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Medicamento", "Medicamentos")
                        .WithMany("FormulaMedicamentos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormulasMedicas");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.HistorialMedico", b =>
                {
                    b.HasOne("Dominio.Entities.Empleado", "Empleados")
                        .WithMany("HistorialesMedicos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Paciente", "Pacientes")
                        .WithMany("HistorialesMedicos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Dominio.Entities.Inventario", b =>
                {
                    b.HasOne("Dominio.Entities.Compra", "Compras")
                        .WithMany("Inventarios")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Farmacia", "Farmacias")
                        .WithMany("Inventarios")
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Venta", "Ventas")
                        .WithMany("Inventarios")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compras");

                    b.Navigation("Farmacias");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Dominio.Entities.Medicamento", b =>
                {
                    b.HasOne("Dominio.Entities.CategoriaMedicamento", "Categorias")
                        .WithMany("Medicamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Presentacion", "Presentaciones")
                        .WithMany("Medicamentos")
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Proveedor", "Proveedores")
                        .WithMany("Medicamentos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.TipoMedicamento", "Tipos")
                        .WithMany("Medicamentos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Presentaciones");

                    b.Navigation("Proveedores");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("Dominio.Entities.MedicamentosComprados", b =>
                {
                    b.HasOne("Dominio.Entities.Compra", "Compras")
                        .WithMany("MedicamentosComprados")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Medicamento", "Medicamentos")
                        .WithMany("MedicamentosComprados")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compras");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.MedicamentosVendidos", b =>
                {
                    b.HasOne("Dominio.Entities.Medicamento", "Medicamentos")
                        .WithMany("MedicamentosVendidos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Venta", "Ventas")
                        .WithMany("MedicamentosVendidos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamentos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Dominio.Entities.Paciente", b =>
                {
                    b.HasOne("Dominio.Entities.Genero", "Generos")
                        .WithMany("Pacientes")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generos");
                });

            modelBuilder.Entity("Dominio.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dominio.Entities.Usuario", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dominio.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Dominio.Entities.Rol", "Roles")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuario", "Usuarios")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Dominio.Entities.Venta", b =>
                {
                    b.HasOne("Dominio.Entities.Usuario", "Usuarios")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.MetodoDePago", "MetodosDePagos")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoDePagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Empleado", "Empleados")
                        .WithMany("Ventas")
                        .HasForeignKey("VentaEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("MetodosDePagos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("Dominio.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entities.CargoEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Dominio.Entities.CategoriaMedicamento", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Ciudad", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("Dominio.Entities.Compra", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("MedicamentosComprados");
                });

            modelBuilder.Entity("Dominio.Entities.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Dominio.Entities.Empleado", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("FormulasMedicas");

                    b.Navigation("HistorialesMedicos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Dominio.Entities.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Dominio.Entities.Farmacia", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Empleados");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Dominio.Entities.FormulaMedica", b =>
                {
                    b.Navigation("FormulaMedicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Genero", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Dominio.Entities.Medicamento", b =>
                {
                    b.Navigation("FormulaMedicamentos");

                    b.Navigation("MedicamentosComprados");

                    b.Navigation("MedicamentosVendidos");
                });

            modelBuilder.Entity("Dominio.Entities.MetodoDePago", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Dominio.Entities.Paciente", b =>
                {
                    b.Navigation("FormulasMedicas");

                    b.Navigation("HistorialesMedicos");
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Presentacion", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Proveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Dominio.Entities.TipoDireccion", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("Dominio.Entities.TipoMedicamento", b =>
                {
                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Dominio.Entities.TipoVia", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("Dominio.Entities.Usuario", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Dominio.Entities.Venta", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("MedicamentosVendidos");
                });
#pragma warning restore 612, 618
        }
    }
}
